<a href="https://colab.research.google.com/github/Dilparao/CE888/blob/master/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1. Create a (4 x 2) integer array and print it's attributes
import numpy as np
x = np.array([[1, 2],[3,4],[5,6],[7,8]])
print(x)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
#2. Create an array of dimension (1,10) and sort it in ascending and descending order
y = np.array([[1,4,9,5,8,34,56,24,2,21]])
print(y.shape)         # dimension of an array
y.sort()
print('The ascending order is '+str(y))               # ascending order
print('The descending order is ' + str(-np.sort(-y)))    # descending order)


(1, 10)
The ascending order is [[ 1  2  4  5  8  9 21 24 34 56]]
The descending order is [[56 34 24 21  9  8  5  4  2  1]]


In [40]:
#3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]
X=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.reshape(X, (3,-1)) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
#4. Stack two arrays of any size horizontally and vertically
a = np.array([2,3,4,5,6])
b = np.array([4,5,6,7,8])
x=np.hstack((a,b))
y=np.vstack((a,b))
print(x)
print(y)
y.ndim

[2 3 4 5 6 4 5 6 7 8]
[[2 3 4 5 6]
 [4 5 6 7 8]]


2

In [47]:
#5. Create two arrays of same size and find common elements
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = np.array([10, 30, 40, 50, 60])
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10 30 40 50 60]
Common values between two arrays:
[10 40 60]


In [74]:
#6. Create a 2D array of 5 X 5 and find the min  and max values of each row
x=([[1,2,3,4,5],[3,6,9,2,11],[9,4,7,5,8],[3,6,5,7,8],[15,6,12,9,8]])

list1=[]
for i in range(5):
  max = 0
  for j in range(5):
    if x[i][j] > max:
      max = x[i][j]
  list1.append(max)
print('The max values of each row is '+str(list1))   

list1=[]
for i in range(5):
  min = 100
  for j in range(5):
    if x[i][j] < min:
      min = x[i][j]
  list1.append(min)
print('The min values of each row is '+str(list1)) 

print ('The maximum values for each column is '+str(np.max(x,axis=0)))
print ('The maximum values for each column is '+str(np.min(x,axis=0)))




The max values of each row is [5, 11, 9, 8, 15]
The min values of each row is [1, 2, 4, 3, 6]
The maximum values for each column is [15  6 12  9 11]
The maximum values for each column is [1 2 3 2 5]


In [95]:
# 7. Create an array of size 100 and compute the mean, median, standard deviation.
from statistics import median
x=np.arange(100)
#print(x)
print('Mean is ',x.mean())
print("Median is "  ,median(x))
print("Standard Deviation: ",x.std())


Mean is  49.5
Median is  49.5
Standard Deviation:  28.86607004772212


In [97]:
#8.Normalize a 5x5 random matrix
import numpy as np
x= np.random.random((5,5))
print("Original Matrix:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Matrix:
[[0.00473739 0.42217594 0.01564741 0.29650552 0.79773977]
 [0.69593061 0.23175355 0.21963862 0.84592275 0.07400499]
 [0.34575677 0.57665122 0.70193476 0.57436397 0.03982438]
 [0.45590897 0.25284819 0.39833242 0.79318077 0.05288591]
 [0.45871    0.11106943 0.40503222 0.23810389 0.67109113]]
After normalization:
[[0.         0.49625038 0.01296981 0.34685355 0.94272014]
 [0.82168955 0.2698765  0.25547429 1.         0.08234523]
 [0.40540338 0.67989038 0.82882728 0.67717129 0.04171137]
 [0.53635216 0.29495378 0.46790524 0.93730041 0.0572389 ]
 [0.53968202 0.12640739 0.47586995 0.27742577 0.79216041]]


In [103]:
#9.Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)
a=np.random.randint(1,10, (4,4,3))
b=np.random.randint(1,10, (4,4))
print(a*b[:,:,None])
 

[[[16 12 16]
  [ 1  4  1]
  [ 7  2  9]
  [ 2  8  8]]

 [[ 4  8  3]
  [ 3  8  7]
  [48 30 18]
  [32  4 32]]

 [[16 36  8]
  [24 48 16]
  [24  8  8]
  [45 45 72]]

 [[ 5  4  5]
  [16 32 16]
  [20  8  8]
  [21 21 56]]]
